version: '2'
services:
    changedetection.io:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection.io
      hostname: changedetection.io
      volumes:
        - ./config:/datastore
      environment:
        - PUID=1000
        - PGID=1000

networks:
  default:
    external: true
    name: homer_default
