---
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/usb/docker/sonarr:/config
      - /mnt/hdd/series:/tv #optional
      - /mnt/hdd/downloads/completed:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
