version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    environment:
      - TZ=Europe/Madrid
      - PGID=1000
      - PUID=1000
    ports:
      - "5800:5800"
    volumes:
      - "/mnt/appdata/docker/jdownloader/config:/config:rw"
      - "/mnt/hdd/downloads-jd:/output:rw"
