---
version: "2.1"
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/appdata/docker/pyload/config:/config
      - /mnt/hdd/downloads-py:/downloads
    ports:
      - 8008:8000
      - 9666:9666 #optional
    restart: unless-stopped
