---
version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/London
      - SUBDOMAINS=pheebs
      - TOKEN=yourtoken
      - LOG_FILE=true #optional
    volumes:
      - ./config:/config 
    restart: unless-stopped
    
networks:
  default:
    external: true
    name: nginx_default
