version: '3.3'
services:
    shlink:
        container_name: shlink
        ports:
            - '8090:8080'
        environment:
            - DEFAULT_DOMAIN=s.dom.duckdns.org
            - IS_HTTPS_ENABLED=true
            - GEOLITE_LICENSE_KEY=s
        image: 'shlinkio/shlink:stable'

    shlink-web-client:
        container_name: shlink-web-client
        ports:
            - '8040:80'
        image: shlinkio/shlink-web-client
        volumes:
            - ./data/servers.json:/usr/share/nginx/html/servers.json

networks:
  default:
    external: true
    name: nginx_default
