version: '3'
services:
  flame:
    image: pawelmalak/flame:multiarch
    container_name: flame
    environment:
      - PASSWORD=password
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/appdata/docker/flame/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005:5005
    restart: unless-stopped

networks:
  default:
    external: true
    name: homer_default
