---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /mnt/appdata/docker/duplicati/config:/config
      - /mnt/appdata/docker:/docker
      - /mnt/hdd:/hdd 
      - /mnt/appdata:/appdata
      - /mnt/hdd/books:/books
    ports:
      - 8200:8200
    restart: unless-stopped

