---
version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/usb/docker/duplicati/config:/config
      - /mnt/hdd/backups:/backups
      - /mnt/usb/docker:/docker
      - /mnt/hdd:/hdd 
      - /mnt/hdd/books:/books
    ports:
      - 8200:8200
    restart: unless-stopped
