version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://192.168.1.154:6875
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=pass
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/appdata/docker/bookstack/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=pass
    volumes:
      - /mnt/appdata/docker/bookstack/mariadb:/config
    restart: unless-stopped

networks:
  default:
    external: true
    name: homer_default
