version: "3"
services:
  invidious:
    image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "3000:3000"
    container_name: invidious
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        default_user_preferences:
          dark_mode: false
          local: true
          locale: "es"
          region: ES
          default_home: Trending
          player_style: youtube
          quality_dash: auto
          quality: dash
          comments: ["youtube",""]    
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - invidious-db

  invidious-db:
    container_name: invidious_db
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - ./config/var:/var/lib/postgresql/data
      - ./config/config/sql:/config/sql
      - ./config/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

networks:
  default:
    external: true
    name: homer_default
