---
version: "2.1"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/usb/docker/radarr:/config
      - /mnt/hdd/movies:/movies
      - /mnt/hdd/downloads/completed:/data/completed
    ports:
      - 7878:7878
    restart: unless-stopped
