---
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /mnt/appdata/docker/calibre-web:/config
      - /mnt/hdd/books:/books
    ports:
      - 8083:8083/tcp
      - 8083:8083/udp
    restart: unless-stopped

