version: '3.7'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:latest
    ports:
      - "8123:8123"
    volumes:
      - /mnt/usb/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always

