version: '3.3'
services:
    homepage:
        image: ghcr.io/benphelps/homepage:latest
        container_name: homepage
        ports:
            - 3333:3000
        volumes:
            - ./config:/app/config
            - /var/run/docker.sock:/var/run/docker.sock 

networks:
  default:
    external: true
    name: homer_default
