version: "3"
services:
  wsgidav:
    container_name: wsgidav
    build: .
    ports:
      - 10280:8080
    restart: unless-stopped
    environment:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - /mnt/appdata:/var/wsgidav-root
