---
version: "2.1"
services:
  scrutiny:
    image: lscr.io/linuxserver/scrutiny
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SCRUTINY_API_ENDPOINT=http://172.31.0.2:9980
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - /mnt/appdata/docker/scrutiny:/config
      - /run/udev:/run/udev:ro
    ports:
      - 9980:8080
    devices:
      - /dev/sda:/dev/sda # hdd 500gb
      - /dev/sdb:/dev/sdb # hdd 1tb
      - /dev/sdc:/dev/sdc # usb
      # - /dev/nvme1n1:/dev/nvme1n1
    restart: unless-stopped