version: '3.3'
services:
    openbooks:
        ports:
            - '888:80'
        volumes:
            - '/mnt/hdd/downloads/books:/books'
        restart: unless-stopped
        container_name: openbooks
        command: --persist
        environment:
         # - BASE_PATH=/openbooks/
          - TZ=Europe/London
          - PGID=1000
          - PUID=1000
        image: evanbuss/openbooks:latest

