---
version: "2.1"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/hdd/lidarr:/config
      - /mnt/hdd/navidrome/music:/music #optional
      - /mnt/hdd/downloads/completed:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
