---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/ #optional
    #  - USER=username #optional
    #  - PASS=password #optional
    #  - WHITELIST=iplist #optional
    #  - PEERPORT=peerport #optional
    #  - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - /mnt/appdata/docker/new-transmission/config:/config
      - /mnt/hdd/downloads:/downloads
    #  - <path to watch folder>:/watch
  #  ports:
  #    - 9092:9091
  #    - 51413:51413
  #    - 51413:51413/udp
    restart: unless-stopped