version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /mnt/appdata/docker/kuma:/app/data
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 3001:3001
    restart: always


networks:
  default:
    external: true
    name: homer_default


